withEnv(["PIPE_FLOW_NUMBER=${currentBuild.number}"]) {
  node {
    stage "checkout, test, build and publish"
    git url: "http://git.nautsch.net/dev/cd-ws-address.git"
    if(isUnix()){
      sh "./gradlew -b ./workspace/build.gradle pushImages --info"

    }
    else{
      // not tested
      bat "gradlew.bat ./workspace/build.gradle pushImages --info"
    }
  }
}
