withEnv(["PIPE_FLOW_NUMBER=${currentBuild.number}"]) {
  node {
    def workspace = pwd()
    if(isUnix()){
      sh "${workspace}/gradlew pushImages --info"

    }
    else{
      bat "${workspace}/gradlew.bat pushImages --info"
    }
  }
}
